### ISSUE TITLE
doubts about the dataset processing part

### ISSUE THREAD

**Issue by dlivxpr** [byminji/SLTtrack#10]
Hello, I would like to ask about the preprocessing methods for the slt-SiamAttn experiment. Are the preprocessing methods the same as pysot? In other words, can I directly use the dataset that has been preprocessed with pysot? The tracking net dataset is too large; can it be replaced with youtube-bb, imagenet det, or imagenet vid?

**Comment by byminji** [comment]
Hi @Jontyshaw , thanks for your interest in our work.

1. Unfortunately, you could not use preprocessing methods (cropping frames with GT+perturbations) in original pysot for our framework because our training framework includes search window cropping based on previous estimations as same as inference time. Thus you need original training images without preprocessing. 

2. You could replace the TrackingNet dataset with other datasets, but this might occur the accuracy decrease. If you want to reduce the cost in TrackingNet training, I recommend to use part of subsets in TrackingNet dataset, e.g., using 0-3 among 12 subsets in training sets.

**Comment by dlivxpr** [comment]
> Hi @Jontyshaw , thanks for your interest in our work.您好，感谢您对我们工作的兴趣。
> 
> 1. Unfortunately, you could not use preprocessing methods (cropping frames with GT+perturbations) in original pysot for our framework because our training framework includes search window cropping based on previous estimations as same as inference time. Thus you need original training images without preprocessing.不幸的是，您无法在我们的框架的原始 pysot 中使用预处理方法（使用 GT+扰动裁剪帧），因为我们的训练框架包括基于先前估计的搜索窗口裁剪，与推理时间相同。因此，您需要未经预处理的原始训练图像。
> 2. You could replace the TrackingNet dataset with other datasets, but this might occur the accuracy decrease. If you want to reduce the cost in TrackingNet training, I recommend to use part of subsets in TrackingNet dataset, e.g., using 0-3 among 12 subsets in training sets.您可以将 TrackingNet 数据集替换为其他数据集，但这可能会导致准确性下降。如果你想降低TrackingNet训练的成本，我建议使用TrackingNet数据集中的部分子集，例如，使用训练集中12个子集中的0-3。

Thank you very much for your answer
