### ISSUE TITLE
About the setting of reward

### ISSUE THREAD

**Issue by zhenzhiwang** [byminji/SLTtrack#7]
Hi, thanks for releasing the code of your great work!

In the paper and code, I notice that you use iou(SLTtracker) - iou(argmax tracker) as per-frame reward and there seems to be no sequence-level reward. Here please correct me if my understanding is wrong. Then I have two questions about this: (1) Since RL could optimize any non-differentiable objectives, why don't directly use the SOT metrics of each sequence to be the reward? (2) Commonly sequence-level RL will use a discount factor gamma to propagate the final reward to each state in the entire sequence. Have you considered to use such discount factors to combine the reward acorss frames?

Thanks again for providing the code of your great work! I hope you could share more thoughts about the setting of reward with me.

Best

**Comment by byminji** [comment]
Hi, great thanks for your interest in our work and for raising good questions!

Before answering your two questions, I'd like to correct that we use a sequence-level reward, not a per-frame reward. For each sequence of frames, we calculate Average Overlap (AO) between predictions and GTs (which is as same as the SOT metric in the GOT-10k dataset) and use this AO as a sequence-level reward. Note that AO is computed as the averaged overlap of GT and prediction for every frame in each video. For more details about our training process, you could refer to `Algorithm 1` in our paper.

And below are answers to your two questions:
(1) Yes, we could directly adopt SOT metrics, e.g., AUC and AO. In our implementation, we simply adopted AO because it is easier to calculate than AUC during training.
(2) We didn't consider such discount factors in our implementation, but I guess adopting it is worth trying for the stability of training.

Thanks :)

**Comment by zhenzhiwang** [comment]
Hi, Thanks for your reply. Maybe I still not truely understand the setting of reward. 

I understand now you use AO of a tracking sequence as a reward. Yet I still confuse that whether the AO is used for each frame of the entire tracking sequence or is just used for the last frame and set all other frames' reward as 0? In other words, I guess that the "state" of your RL algorithm is a H*W feature map and the "action" is a distribution of such H*W feature map to select which point for regress bbox. Then, the reward is also needed to be frame-level. I understand that your reward is computed by sequence-level, yet how it is set to be frame-level for the RL training? Is it copied by T times for each frame or is it just used for the last frame? The reason of my question is that I believe the training unit for RL is a <state, action, reward> tuple, yet obviously the frame-level state and action have a gap with the sequence-level reward. 

Thanks!

**Comment by byminji** [comment]
We build our RL algorithm by corresponding state, action, and reward at time t to o_t (observation, which includes HW feature map as you said), l_t (prediction), and r(l_t, g_t) (reward), respectively. As you pointed out, we need the reward for each timestamp. In this regard, we use AO obtained from the sequence as the reward for all states, i.e., copy AO by T times for each frame.

**Comment by zhenzhiwang** [comment]
Thanks for your kind reply!
